# ---
# Enable code reloading in local mode (development)
#
# Ref: https://roadrunner.dev/docs/beep-beep-reload
reload:
  patterns: [".php"]
  services:
    http:
      recursive: true
      ignore: ["vendor"]
      patterns: [".php", ".env", ".lock"]
      dirs: ["."]
