---
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    working_dir: /app
    command: overmind start -f Procfile.dev

    # Set these env variables using `export FIXUID=$(id -u) FIXGID=$(id -g)`
    user: ${FIXUID:-1000}:${FIXGID:-1000}

    environment:
      - PYROSCOPE_APPLICATION_NAME=my.php.app
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040

    cap_add:
      - SYS_PTRACE

    depends_on:
      - mailhog
      - pgsql
      - pyroscope
      - redis

    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - .:/app:cached

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

  pgsql:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE:-laravel}
      - POSTGRESQL_USERNAME=${DB_USERNAME:-user}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-secret}

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
      start_period: 5s

    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - pgsql:/bitnami/postgresql

  pyroscope:
    image: pyroscope/pyroscope:latest
    command: server

    ports:
      - "${FORWARD_PYROSCOPE_PORT:-4040}:4040"
    volumes:
      - pyroscope:/var/lib/pyroscope

  redis:
    image: bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
      start_period: 5s

    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/bitnami/redis/data

volumes:
  pgsql:
    driver: local
  pyroscope:
    driver: local
  redis:
    driver: local
